### Example Kubernetes Deployment
apiVersion: v1
kind: Namespace
metadata:
  name: reticulum
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rns-storage
  namespace: reticulum-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnsd
  labels:
    app: rnsd
  namespace: reticulum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rnsd
  template:
    metadata:
      labels:
        app: rnsd
    spec:
      containers:
      - name: rnsd
        image: ghcr.io/ghostmeshlabs/reticulum-router:v0.1.3
        imagePullPolicy: Always
        volumeMounts:
          - name: storage
            mountPath: /root/.config/reticulum/
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: rns-storage
---
apiVersion: v1
kind: Service
metadata:
  name: backbone
  namespace: reticulum
spec:
  type: NodePort
  ports:
  - name: public
    nodePort: 30042
    port: 4242
    protocol: TCP
  selector:
    app: rnsd
